### ISSUE TITLE
libcork.a: error adding symbols: file format not recognized

### ISSUE THREAD

**Issue by petronny** [bartoszek/AUR-cloudcompare#18]
```
FAILED: plugins/core/Standard/qCork/libQCORK_PLUGIN.so 
: && /usr/bin/c++ -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -fpermissive -DSUPPORT_TOPO_STREAM_OPERATORS -Wno-deprecated-declarations -fopenmp -O3 -DNDEBUG  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -shared -Wl,-soname,libQCORK_PLUGIN.so -o plugins/core/Standard/qCork/libQCORK_PLUGIN.so plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/QCORK_PLUGIN_autogen/mocs_compilation.cpp.o plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/src/qCork.cpp.o plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/src/ccCorkDlg.cpp.o plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/QCORK_PLUGIN_autogen/EWIEGA46WW/qrc_qCork.cpp.o  -Wl,-rpath,/build/cloudcompare/src/build/libs/CCPluginAPI:/build/cloudcompare/src/build/libs/qCC_glWindow:/build/cloudcompare/src/build/libs/qCC_io:/build/cloudcompare/src/build/libs/qCC_db:/build/cloudcompare/src/build/libs/qCC_db/extern/CCCoreLib:/build/cloudcompare/src/build/libs/CCFbo:  libs/CCPluginAPI/libCCPluginAPI.so  libs/CCPluginStub/libCCPluginStub.a  /build/cloudcompare/src/cloudcompare-cork/lib/libcork.a  /usr/lib/libmpir.so  libs/qCC_glWindow/libQCC_GL_LIB.so  libs/qCC_io/libQCC_IO_LIB.so  libs/qCC_io/extern/dxflib/libdxflib.a  libs/qCC_io/extern/shapelib/libshapelib.a  /usr/lib/libgdal.so  libs/qCC_db/libQCC_DB_LIB.so  libs/qCC_db/extern/CCCoreLib/libCCCoreLib.so  /usr/lib/libgmpxx.so  /usr/lib/libmpfr.so  /usr/lib/libgmp.so  /usr/lib/libQt5Concurrent.so.5.15.7  libs/CCFbo/libCC_FBO_LIB.so  /usr/lib/libQt5OpenGL.so.5.15.7  /usr/lib/libQt5Widgets.so.5.15.7  /usr/lib/libQt5OpenGLExtensions.a  /usr/lib/libQt5Gui.so.5.15.7  /usr/lib/libQt5Core.so.5.15.7  /usr/lib//libQt5Gui.so  /usr/lib//libQt5Core.so  /usr/lib/libGL.so && :
/usr/bin/ld: /build/cloudcompare/src/cloudcompare-cork/lib/libcork.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
[387/736] Building CXX object plugins/core/Standard/qCSF/CMakeFiles/QCSF_PLUGIN.dir/QCSF_PLUGIN_autogen/mocs_compilation.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
```
https://github.com/arch4edu/cactus/actions/runs/3583606576/jobs/6033047190

**Comment by petronny** [comment]
Building cork with `g++` instead of the default `clang++` fixes the problem.

**Comment by AchmadFathoni** [comment]
The latest AUR should fix this.

**Comment by petronny** [comment]
The error still exists: https://github.com/arch4edu/cactus/actions/runs/5745740445/job/15574181043

**Comment by Sir-Photch** [comment]
Also having this issue:
<details>
<summary>Build failure</summary>

```
[533/806] Linking CXX shared library plugins/core/Standard/qCork/libQCORK_PLUGIN.so
FAILED: plugins/core/Standard/qCork/libQCORK_PLUGIN.so
: && /usr/lib/ccache/bin/c++ -fPIC -march=native -O3 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -fpermissive -DSUPPORT_TOPO_STREAM_OPERATORS -Wno-deprecated-declarations -fopenmp -O3 -DNDEBUG  -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto -shared -Wl,-soname,libQCORK_PLUGIN.so -o plugins/core/Standard/qCork/libQCORK_PLUGIN.so plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/QCORK_PLUGIN_autogen/mocs_compilation.cpp.o plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/src/qCork.cpp.o plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/src/ccCorkDlg.cpp.o plugins/core/Standard/qCork/CMakeFiles/QCORK_PLUGIN.dir/QCORK_PLUGIN_autogen/EWIEGA46WW/qrc_qCork.cpp.o  -Wl,-rpath,/home/chris/.cache/paru/clone/cloudcompare/src/build/libs/CCPluginAPI:/home/chris/.cache/paru/clone/cloudcompare/src/build/libs/qCC_glWindow:/home/chris/.cache/paru/clone/cloudcompare/src/build/libs/qCC_io:/home/chris/.cache/paru/clone/cloudcompare/src/build/libs/qCC_db:/home/chris/.cache/paru/clone/cloudcompare/src/build/libs/qCC_db/extern/CCCoreLib:/home/chris/.cache/paru/clone/cloudcompare/src/build/libs/CCFbo:  libs/CCPluginAPI/libCCPluginAPI.so  libs/CCPluginStub/libCCPluginStub.a  /home/chris/.cache/paru/clone/cloudcompare/src/cloudcompare-cork/lib/libcork.a  /usr/lib/libmpir.so  libs/qCC_glWindow/libQCC_GL_LIB.so  libs/qCC_io/libQCC_IO_LIB.so  libs/qCC_io/extern/dxflib/libdxflib.a  libs/qCC_io/extern/shapelib/libshapelib.a  /usr/lib/libgdal.so  libs/qCC_db/libQCC_DB_LIB.so  libs/qCC_db/extern/CCCoreLib/libCCCoreLib.so  /usr/lib/libtbb.so.12.12  /usr/lib/libgmpxx.so  /lib/libmpfr.so  /lib/libgmp.so  /usr/lib/libQt5Concurrent.so.5.15.13  libs/CCFbo/libCC_FBO_LIB.so  /usr/lib/libQt5OpenGL.so.5.15.13  /usr/lib/libQt5Widgets.so.5.15.13  /usr/lib/libQt5OpenGLExtensions.a  /usr/lib/libQt5Gui.so.5.15.13  /usr/lib/libQt5Core.so.5.15.13  /usr/lib//libQt5Gui.so  /usr/lib//libQt5Core.so  /usr/lib/libGL.so && :
/usr/bin/ld: /home/chris/.cache/paru/clone/cloudcompare/src/cloudcompare-cork/lib/libcork.a: error adding symbols: file format not recognized
```

</details>

**Comment by Sir-Photch** [comment]
Apparently, commit https://github.com/bartoszek/AUR-cloudcompare/commit/8159e2b579f7da38abdb2b093a7c3cb7182b8970# causes this issue; By just re-adding `CXX="g++"`, it builds fine.

```patch
diff --git a/PKGBUILD b/PKGBUILD
index b93f398..8555512 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -117,7 +117,7 @@ build() {
         -DJsonCpp_LIBRARY=/usr/lib
   )
   msg2 "Build Cork lib"
-  make -C "${srcdir}/${name}-cork" CXXFLAGS="$CXXFLAGS -DSUPPORT_TOPO_STREAM_OPERATORS -fPIC"
+  make -C "${srcdir}/${name}-cork" CXXFLAGS="$CXXFLAGS -DSUPPORT_TOPO_STREAM_OPERATORS -fPIC" CXX="g++"
   msg2 "Build CloudCompare"
   cmake -B build -S "${srcdir}/${name}" -G Ninja "${CMAKE_FLAGS[@]}"
 # shellcheck disable=SC2086 # allow slitting for MAKEFLAGS carrying multiple flags.

```

**Comment by bartoszek** [comment]
fixed 4bd07177a95aad923cc2e2da5f473b06ed6646f2
